apiVersion: v2
name: concourse
type: application
version: 20.0.1
appVersion: 8.0.1
description: Concourse is a simple and scalable CI system.
icon: https://avatars1.githubusercontent.com/u/7809479
keywords:
  - ci
  - concourse
  - concourse.ci
home: https://concourse-ci.org/
sources:
  - https://github.com/concourse/concourse-chart
  - https://github.com/concourse/concourse
maintainers:
  - name: concourse-team
    email: team@concourse-ci.org
engine: gotpl
