{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "concourse.postgresql.fullname" . }}-connection"
  {{- if .Values.postgresql.secretAnnotations }}
  annotations: "{{ toYaml .Values.postgresql.primary.annotations | nindent 4 }}"
  {{- end }}
  labels:
    app: {{ template "concourse.postgresql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- with .Values.postgresql.labels }}
{{ toYaml . | trim | indent 4 }}
    {{- end }}
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc }}
  {{- with .Values.postgresql.sensitive_environment }}
{{ toYaml . | trim | indent 2 }}
  {{- end }}

{{- end }}
