apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "concourse.web.fullname" . }}
  labels:
    app: {{ template "concourse.web.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  main-team.yml: {{ default "" .Values.concourse.web.auth.mainTeam.config | quote }}
  config-rbac.yml: {{ default "" .Values.concourse.web.configRBAC | quote }}
