{{- if .Values.worker.enabled -}}
{{- if .Values.podSecurityPolicy.create -}}
apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: {{ template "concourse.worker.fullname" . }}
  labels:
    app: {{ template "concourse.worker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - 'CAP_FOWNER'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  volumes:
{{ toYaml .Values.podSecurityPolicy.allowedWorkerVolumes | indent 4 }}
  runAsUser:
    rule: 'RunAsAny'
  runAsGroup:
    rule: 'RunAsAny'    
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
{{- end -}}
{{- end }}
