{{- if .Values.worker.enabled -}}
{{- if eq .Values.worker.kind "StatefulSet" }}
apiVersion: {{ template "concourse.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ template "concourse.worker.fullname" . }}
  labels:
    app: {{ template "concourse.worker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ template "concourse.worker.fullname" . }}
  {{- if not .Values.concourse.worker.autoscaling.maxReplicas }}
  replicas: {{ .Values.worker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "concourse.worker.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "concourse.worker.fullname" . }}
        release: "{{ .Release.Name }}"
        {{- with .Values.worker.labels }}
{{ toYaml . | trim | indent 8 }}
        {{- end }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/worker-secrets.yaml") . | sha256sum }}
  {{- if .Values.worker.annotations }}
{{ toYaml .Values.worker.annotations | indent 8 }}
      {{- end }}
    spec:
    {{- if .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 8 }}
    {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "concourse.worker.fullname" . }}{{ else }}{{ .Values.rbac.workerServiceAccountName }}{{ end }}
      {{- if .Values.worker.tolerations }}
      tolerations:
{{ toYaml .Values.worker.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.worker.priorityClassName }}
      priorityClassName: {{ .Values.worker.priorityClassName }}
      {{- end }}
      {{- if .Values.worker.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if or .Values.worker.cleanUpWorkDirOnStart .Values.worker.extraInitContainers }}
      initContainers:
      {{- end }}
      {{- if .Values.worker.extraInitContainers }}
      {{- toYaml .Values.worker.extraInitContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.cleanUpWorkDirOnStart }}
        - name: {{ template "concourse.worker.fullname" . }}-init-rm
          {{- if .Values.imageDigest }}
          image: "{{ .Values.image }}@{{ .Values.imageDigest }}"
          {{- else }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          command:
            - /bin/bash
          args:
            - -ce
            - |-
              for v in $((btrfs subvolume list --sort=-ogen "{{ .Values.concourse.worker.workDir }}" || true) | awk '{print $9}'); do
                (btrfs subvolume show "{{ .Values.concourse.worker.workDir }}/$v" && btrfs subvolume delete "{{ .Values.concourse.worker.workDir }}/$v") || true
              done
              rm -rf "{{ .Values.concourse.worker.workDir }}/*"
          volumeMounts:
            - name: concourse-work-dir
              mountPath: {{ .Values.concourse.worker.workDir | quote }}
      {{- end }}
      containers:
      {{- if .Values.worker.sidecarContainers }}
      {{- toYaml .Values.worker.sidecarContainers | nindent 8 }}
      {{- end }}
        - name: {{ template "concourse.worker.fullname" . }}
          {{- if .Values.imageDigest }}
          image: "{{ .Values.image }}@{{ .Values.imageDigest }}"
          {{- else }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          args:
            - worker
{{- if .Values.worker.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.worker.livenessProbe | indent 12 }}
{{- end }}
{{- if .Values.worker.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.worker.readinessProbe | indent 12 }}
{{- end }}
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/bash"
                  - "/pre-stop-hook.sh"
          env:
{{- include "concourse.worker.env" . | indent 12 }}
{{- if .Values.worker.env }}
{{ toYaml .Values.worker.env | indent 12 }}
{{- end }}
          ports:
            - name: worker-hc
              containerPort: {{ .Values.concourse.worker.healthcheckBindPort }}
{{- if .Values.worker.additionalPorts }}
{{ toYaml .Values.worker.additionalPorts | indent 12 }}
{{- end }}
{{- if .Values.worker.resources }}
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
{{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: concourse-keys
              mountPath: {{ .Values.worker.keySecretsPath | quote }}
              readOnly: true
            - name: concourse-work-dir
              mountPath: {{ .Values.concourse.worker.workDir | quote }}
            - name: pre-stop-hook
              mountPath: /pre-stop-hook.sh
              subPath: pre-stop-hook.sh
            {{- if and (not (kindIs "invalid" .Values.secrets.workerAdditionalCerts)) (.Values.secrets.workerAdditionalCerts | toString) }}
            - name: worker-additional-certs
              mountPath: "{{ .Values.worker.certsPath }}/worker-additional-certs.pem"
              subPath: worker-additional-certs.pem
              readOnly: true
            {{- end }}

{{- if .Values.worker.additionalVolumeMounts }}
{{ toYaml .Values.worker.additionalVolumeMounts | indent 12 }}
{{- end }}
      affinity:
{{- if .Values.worker.additionalAffinities }}
{{ toYaml .Values.worker.additionalAffinities | indent 8 }}
{{- end }}
        podAntiAffinity:
          {{- if .Values.worker.hardAntiAffinity }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
{{- if .Values.worker.hardAntiAffinityLabels }}
{{ toYaml .Values.worker.hardAntiAffinityLabels | indent 16 }}
{{- else }}
                app: {{ template "concourse.worker.fullname" . }}
                release: {{ .Release.Name | quote }}
{{- end }}
            topologyKey: kubernetes.io/hostname
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "concourse.worker.fullname" . }}
                  release: {{ .Release.Name | quote }}
          {{- end }}
      volumes:
{{- if .Values.worker.additionalVolumes }}
{{ toYaml .Values.worker.additionalVolumes | indent 8 }}
{{- end }}
        - name: pre-stop-hook
          configMap:
            name: {{ template "concourse.worker.fullname" . }}
        - name: concourse-keys
          secret:
            secretName: {{ template "concourse.worker.fullname" . }}
            defaultMode: 0400
            items:
              - key: host-key-pub
                path: host_key.pub
              - key: worker-key
                path: worker_key
        {{- if and (not (kindIs "invalid" .Values.secrets.workerAdditionalCerts)) (.Values.secrets.workerAdditionalCerts | toString) }}
        - name: worker-additional-certs
          secret:
            secretName: {{ template "concourse.worker.fullname" . }}
            optional: true
            items:
              - key: worker-additional-certs
                path: worker-additional-certs.pem
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: concourse-work-dir
      {{- if .Values.persistence.worker.labels }}
        labels:
      {{- with .Values.persistence.worker.labels }}
{{ toYaml . | trim | indent 10 }}
      {{- end }}
      {{- end }}
      spec:
      {{- if .Values.persistence.worker.selector }}
        selector: {{- .Values.persistence.worker.selector | toYaml | nindent 10 }}
      {{- end }}
        accessModes:
          - {{ .Values.persistence.worker.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.worker.size | quote }}
      {{- if .Values.persistence.worker.storageClass }}
      {{- if (eq "-" .Values.persistence.worker.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.worker.storageClass }}"
      {{- end }}
      {{- end }}
  {{- else }}
      {{ if include "concourse.are-there-additional-volumes.with-the-name.concourse-work-dir" . | not }}
        - name: concourse-work-dir
          emptyDir:
            {{- if .Values.worker.emptyDirSize }}
            sizeLimit: {{ .Values.worker.emptyDirSize | quote }}
            {{- end }}
      {{- end }}
  {{- end }}
  {{- if semverCompare "^1.7-0" .Capabilities.KubeVersion.GitVersion }}
  updateStrategy:
{{ toYaml .Values.worker.updateStrategy | indent 4 }}
  {{- end }}
  {{- if .Values.worker.podManagementPolicy }}
  podManagementPolicy: {{ .Values.worker.podManagementPolicy }}
  {{- end }}
{{- end }}
{{- end }}
