{{- if .Values.worker.enabled  }}
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "concourse.worker.fullname" . }}
  labels:
    app: {{ template "concourse.worker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.secrets.annotations }}
  annotations:
{{ toYaml .Values.secrets.annotations | indent 4 }}
  {{- end }}
type: Opaque
data:
  host-key-pub: {{ .Values.secrets.hostKeyPub | b64enc | quote }}
  worker-key: {{ .Values.secrets.workerKey | b64enc | quote }}
  {{- if and (not (kindIs "invalid" .Values.secrets.workerAdditionalCerts)) (.Values.secrets.workerAdditionalCerts | toString) }}
  worker-additional-certs: {{ .Values.secrets.workerAdditionalCerts | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
