{{- if .Values.worker.enabled -}}
{{- if .Values.rbac.create -}}
{{- if .Values.podSecurityPolicy.create -}}
apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
kind: Role
metadata:
  name: {{ template "concourse.worker.fullname" . }}
  labels:
    app: {{ template "concourse.worker.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "concourse.worker.fullname" . }}
  verbs:
  - use
{{- end -}}
{{- end -}}
{{- end }}
