apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "concourse.worker.fullname" . }}
  labels:
    app: {{ template "concourse.worker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  pre-stop-hook.sh: |
    #!/bin/bash
    while true; do
      kill -s {{ .Values.concourse.worker.shutdownSignal }} 1
      for i in {0..60}; do
        sleep 1
        if ! [ -e /proc/1 ]; then
          exit 0
        fi
      done
    done
